# Generated by Django 3.2 on 2022-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_auto_20220504_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=120, max_digits=6),
            preserve_default=False,
        ),
    ]
