# Generated by Django 3.2 on 2022-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_alter_payment_total_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
