# Generated by Django 4.0.3 on 2022-05-21 19:09

import Staff.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_auto_20220504_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[Staff.models.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[Staff.models.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
