# Generated by Django 4.0.3 on 2022-05-23 13:06

import Staff.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_alter_payment_amount_owed_alter_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[Staff.models.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[Staff.models.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_tipped',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
