# Generated by Django 4.0.3 on 2022-05-20 22:43

import Booking.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_visit',
            field=models.DateField(validators=[Booking.utils.validate_date]),
        ),
    ]
