# Generated by Django 4.0.3 on 2022-05-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_alter_booking_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
