# Generated by Django 3.2 on 2022-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20220425_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
