# Generated by Django 4.0.4 on 2022-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_time_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bill_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
