# Generated by Django 4.0.3 on 2022-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_booking_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
