# Generated by Django 4.0.3 on 2022-05-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_booking_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.IntegerField(default=''),
        ),
    ]
