# Generated by Django 4.0.3 on 2022-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_booking_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
