# Generated by Django 3.2 on 2022-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_alter_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_no_show',
            field=models.BooleanField(default=False),
        ),
    ]
