# Generated by Django 4.0.4 on 2022-05-22 23:15

import Booking.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_booking_no_show_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='disabled_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(validators=[Booking.models.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
