# Generated by Django 4.0.4 on 2022-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_booking_disabled_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_info',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
