# Generated by Django 4.0.4 on 2022-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_booking_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
    ]
