# Generated by Django 4.0.3 on 2022-05-23 11:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_alter_booking_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
