# Generated by Django 4.0.3 on 2022-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_alter_booking_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
