# Generated by Django 4.0.3 on 2022-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.CharField(default='5 Star', max_length=6),
            preserve_default=False,
        ),
    ]
