# Generated by Django 3.2 on 2022-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
