# Generated by Django 4.0.3 on 2022-05-20 23:20

import Reviews.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_acknowledged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(validators=[Reviews.utils.validate_not_spaces]),
        ),
        migrations.AlterField(
            model_name='review',
            name='first_name',
            field=models.CharField(max_length=25, validators=[Reviews.utils.validate_not_spaces]),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_name',
            field=models.CharField(max_length=25, validators=[Reviews.utils.validate_not_spaces]),
        ),
    ]
