# Generated by Django 4.0.3 on 2022-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('1 Star', '1 star'), ('2 Star', '2 star'), ('3 Star', '3 star'), ('4 Star', '4 star'), ('5 Star', '5 star')], max_length=6),
        ),
    ]
