# Generated by Django 4.0.3 on 2022-05-31 06:45

import Reviews.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(validators=[Reviews.utils.validate_not_spaces, django.core.validators.MinLengthValidator(80, 'The field must contain at least 50 characters')]),
        ),
    ]
