# Generated by Django 4.0.4 on 2022-06-01 13:21

import Reviews.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(validators=[Reviews.utils.validate_not_spaces, django.core.validators.MinLengthValidator(80, 'The field must contain at least 80 characters')]),
        ),
    ]
